### ISSUE TITLE
Error while publishing in Single Site Mode

### ISSUE THREAD

**Issue by bhandarys** [silexlabs/Silex#1171]
Hi, I have followed the following link to create a  custom hosting provider

https://github.com/silexlabs/Silex/wiki/Integrate-Silex-with-your-infrastructure#create-a-hosting-provider

I have created a folder called Website within my NodeJS project. When I click on publish
1. I get a screen with message "I am about to publish your site. This may take several minutes". However in the console I can see an error - XML Parsing Error: no root element found
Location: http://localhost:6805/tasks/publish
Line Number 1, Column 1:

2. After some time, I get a message "I did not manage to publish the website. No pending publication". In the console, I see the following error - ET | http://localhost:6805/tasks/publishState Status: 404 Not Found.

Am I doing something wrong?

My versions are:
Node: 14.16.1
"silex-website-builder": "^2.7.29",
OS: Windows 10
Browsers: 
Firefox (version 98.0)
Chrome (version 98.0.4758.102)

**Comment by lynnmedia** [comment]
Please remove me from your distribution list. I have unsubscribed, but you keep sending them. I have set all of my notification settings off, but I keep receiving them. I closed my account at GitHub in order to stop getting these f'in messages all day but they keep coming. My next stop is to take down your servers and shut down everything you do, so please, first just remove my name so I get no more emails and you're safe. Otherwise you cursed, in the name of God, to perish immediately. Om namo bhagavate vasudevaya

**Comment by lexoyo** [comment]
>     1. I get a screen with message "I am about to publish your site. This may take several minutes". However in the console I can see an error - XML Parsing Error: no root element found
>        Location: http://localhost:6805/tasks/publish
>        Line Number 1, Column 1:

This is a warning right?
It is not a problem, this is because the publish service returns an empty string

>     2. After some time, I get a message "I did not manage to publish the website. No pending publication". In the console, I see the following error - ET | http://localhost:6805/tasks/publishState Status: 404 Not Found.

This probably means you are trying to publish to a non existing folder OR to publish a non existing file. Could you check that both the file and the folder exist? Then maybe send me more details?

**Comment by bhandarys** [comment]
Hi Alex, I got a mail with your response. But the response seems to be missing here. Can you please guide me the folder where the custom hosting provider example, saves by default?

**Comment by lexoyo** [comment]
Hi @bhandarys 
Did you sort it out? You need to select an existing folder when publishing

**Comment by lexoyo** [comment]
Or maybe it is another error

**Comment by bhandarys** [comment]
Hi Alex, Sorry about the delay. Yes, I had managed to solve this problem. Thank you for your help.
