### ISSUE TITLE
cant change Background image

### ISSUE THREAD

**Issue by konsumopfer77** [silexlabs/Silex#1191]
Not all the time but almost all the time this error occures when i'm trying to change the background image:

![334343434](https://user-images.githubusercontent.com/44984803/176321795-3ca77ff1-634b-4335-ba56-b33ec43517b9.png)

Am i missing something there? One way to work arround would be to just rename the new picture and replace the old one but its annoying if you are just trying things out.

**Comment by lexoyo** [comment]
Hello
Sorry I did not get the notification for your question
(and @ceubri @gtiani @fernandammoutinhobarros @BaguetteAgile are probably in vacation :stuck_out_tongue: )

Would you please give me some context @konsumopfer77 ?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'

**Expected behavior**
A clear and concise description of what you expected to happen.

**If you use Silex online, please complete the following information**
 - URL: [e.g. editor.silex.me]
 - Browser [e.g. chrome, safari]

**If you use Silex desktop app, please complete the following information**
 - Silex desktop version: [e.g. v2.7.23]
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, safari]

**Comment by BaguetteAgile** [comment]
@konsumopfer77 

Hi, do you still have this problem?
what is the weight of your background image and the format?
