### ISSUE TITLE
few successive ctrl+Z delete all

### ISSUE THREAD

**Issue by oliviermgx** [silexlabs/Silex#1569]
Using ctrl+Z in the interface works at the beginning, but if we make few ctrl+Z one after others, at about 10 times or less, all the site is deleted.

**Comment by lexoyo** [comment]
Ok i reproduce it, thank you !

I believe the problem comes from these lines... In case you want to check it out (and for me to remember if I do it)
https://github.com/silexlabs/Silex/blob/dev/src/ts/client/index.ts#L94

Probably they execute before grapesjs had time to parse the data or something

There is an event that i recently discobered which might be worth listening to, it may come after the parsing: `canvas:frame:load`. It is a [GrapesJS event](https://grapesjs.com/docs/api/editor.html#available-events) and here is [how i used it](https://github.com/silexlabs/Silex/commit/3e7bc3aeeaa93436cd3e23c0ae1e434433a68b54#diff-829a43fd501ecd4effd94d573e70de7881aa94b1fac66f50f177102b32177ccbL91). It might be a good idea to check if it would fix the bug by using this event in place of the setTimeout, or in addition to it

Talk to you soon!

**Comment by oliviermgx** [comment]
solved
see ctrlZ_branch_v2

**Comment by lexoyo** [comment]
ok great @oliviermgx !!! this is merged and will be live in the next release :fireworks:
