### ISSUE TITLE
wether 'saving' nor publish webpaghe is working.

### ISSUE THREAD

**Issue by LeOS-GSI** [silexlabs/Silex#1587]
I have tried to save / publish a webpage in Git, FTP and Webdav, but I'm always getting an error:  
`Error: I did not manage to save the file. Could not complete action writefile: Cannot create file here. `

I'm using your web interface, because you Desktop is not starting. see issue #1586

How can I save the webpage locally on my Desktop ??

**Comment by lexoyo** [comment]
Hello

First of all if you are just starting your project you should use the next version v3 instead because support for the v2 has stopped - I wrote it in several places but I know it is easy to miss, I'm working on a new website which will make that obvious
https://v3.silex.me
https://docs.silex.me/en/user/faq#how-to-get-started-with-silex

Then I am sorry to hear that v2 gives you hard times, let me know if you can not use v3 I will help

**Comment by LeOS-GSI** [comment]
Hi

thanks for reply. The v3 is working and I can save the files. Good job. 
Is there also a Linux Appimge of 3 ? or can I build it by my own ?

**Comment by lexoyo** [comment]
for now no appimage of the v3
would you build your own with electron?
