### ISSUE TITLE
Silex CSS editor

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#184]
This documentation was [moved to SIlex wiki, on this page](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor)

**Comment by lexoyo** [comment]
This page needs an examples for each class available in Silex

**Comment by Barbolux** [comment]
Silex Team, thanks for the good work. A comment: Once you updated the software Silex to "apollo mode always", would be usefull if you update these questions and answers, since this is being documentation for us users and some parts became misunderstood for me. I was looking for the Tools menu for a long time before became aware of the UI changes.

**Comment by lexoyo** [comment]
This documentation was [moved to SIlex wiki, on this page](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor)
