### ISSUE TITLE
Error: I did not manage to save the file

### ISSUE THREAD

**Issue by blauer** [silexlabs/Silex#249]
Error: I did not manage to save the file
I did some changes to my already existing Website, when i wanted to save to my Dropbox-Folder i got this error. I tried several times with different Browsers and other Dropbox accounts. Nothing worked.
Can you tell me what leads to this problem, and how i can solve it?

greetings from Germany,
David

**Comment by lexoyo** [comment]
hi @blauer 
can you try again now please?

**Comment by blauer** [comment]
Hello,
its working like a charm again. 
Thanks a lot!

**Comment by lexoyo** [comment]
Ok cool :v: 

Silex app is node.js [hosted by gandi](https://www.gandi.net/supports/#silex), and sometimes the app goes unresponsive, often because of Dropbox auth.. 

You can check if this is the problem and even be notified when Silex goes down with this [Silex status twitter account](https://twitter.com/status_silex). If the last tweet says "PROBLEM Alert" then it is not you but it is Silex or one of its components which is down.
