### ISSUE TITLE
Links Quit Working 

### ISSUE THREAD

**Issue by promoviper** [silexlabs/Silex#250]
All of my links quit working.  They appear to be functioning in the address field at the top of chrome but the pages are not changing.  Also object size and positioning tools no longer work.

**Comment by lexoyo** [comment]
hi @promoviper 
can you share the website with me on dropbox please? my dropbox address is a.hoyau [at] im-paris [dot] fr

**Comment by promoviper** [comment]
index.html
|   |
|   |  |   |   |   |   |   |
| index.htmlShared with Dropbox |
|  |
| View on www.dropbox.com | Preview by Yahoo |
|  |
|   |

**Comment by promoviper** [comment]
https://www.dropbox.com/sh/087emhbcy5kybpc/AABMkpRiUn7eHJnh-lO2B9O8a?dl=0 
heres a link to the entire folder

**Comment by promoviper** [comment]
I made a brand new folder.  Recreated 3 of the pages and the links now work.  Does that make any sense?  Also, how do I go about donating?

**Comment by promoviper** [comment]
I think I have narrowed down the issue.  It seems to have something to do with the embedded slider on the main page.

**Comment by lexoyo** [comment]
I suppose you fixed it because when I display the website you shared on dropbox the links work

But one important thing I have noticed: it looks like you have saved your website with Silex version 2.2.4 from preprod.silex.me and the edited it again with Silex 2.2.3 from editor.silex.me. This is a problem because Silex upgraded your website to 2.2.4 and the data is stored differently. I did not think of the case where you would go back :'(

Do you have a backup of your site before your tests on preprod? Otherwise I will have to clean it up by hand

**Comment by promoviper** [comment]
I just rebuilt the entire site from the ground up.  Thank you for your help.  I figured that had something to do with it.  I quit using the preprod editor.  The image slider I embedded in the page however kills my links and makes the site not function for now I just left it off any ideas why it would do that?


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by lexoyo** [comment]
If you want I can debug this, just send me the code of the slider
Bye!
