### ISSUE TITLE
why static.silex.me?

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/Silex#293]
Hi,

just wondering 2 things:

Why is static.silex.me inside this repo? I understand you use it for serving static content, but why isn't it a different repo?

Or even better, why do you need the app to depend on `static.silex.me`? Couldn't you ship library directly from the repo?

Just wondering :)

**Comment by lexoyo** [comment]
Very good question :)

The websites you make with silex need to include these scripts with an absolute path, so I decided to put them on a different sub domain and one day serve them from a cdn. For now they are on a cheap hosting which does not need nodejs to serve these static files

But I'm still wondering if I should serve them with nodejs... Or put this code in a different repo... What do you thik?

**Comment by pierreozoux** [comment]
I like when everything is under my control, so by default, I believe it should be served by node.

Then as a second step, for some people it might come handy to have the possibility to serve static content with a CDN. Do you have performance issue on your server?

When you do, (or somebody else), we could tune the  `grunt build` task that would read ENV variable for CDN_URL for instance, and if present, prepend CDN_URL.

The command then would be: `CDN_URL=https://cloudfront.net/ grunt build`

Using [grunt-env](https://www.npmjs.com/package/grunt-env) and [grunt-cdn](https://www.npmjs.com/package/grunt-cdn)

I think this would be the most elegant solution. (Sorry you asked me what I think :) )

The other option would be to use the officials cdn. It would be a bit cleaner than now.
This way I could serve `silex` over https (which I can't right now, as static.silex.me doesn't offer the option)

**Comment by lexoyo** [comment]
> Do you have performance issue on your server?

Not I don't. For the only "official" instance for now I have only 1 server "simple hosting" from gandi..

> I think this would be the most elegant solution. (Sorry you asked me what I think :) )

I like to use env vars.. 
Since the websites need to have full URLs for the scripts embeded into the websites, I believe I could use a CDN_URL which would default in http://static.silex.me

Oh and another reason why I have a static folder, is that the scripts embeded in silex websites do not need to be updated when there is a new version of Silex, but only when I save the website. So I had to keep 2.0, 2.1, ...., 2.5 available online. 

I guess I will keep a static folder in the repo and serve it with nodejs.

PS: I am in the process of removing grunt and use only npm / sh scripts.

**Comment by pierreozoux** [comment]
Ah ok, didn't think about the generated websites.

I let you decide what is the best for you :)
