### ISSUE TITLE
publishing problem

### ISSUE THREAD

**Issue by darthswad** [silexlabs/Silex#327]
Hey, i have just created a website. Everything looks perfect in the editor and in preview. But the published version.. when i click the index file, the fields are are jumbled up. Meaning that the containers are in wrong locations, etc. Any advice?

**Comment by lexoyo** [comment]
Hi
You can not just click on the file and expect it to look fine, but you can preview your website and change the file name to `index.html`. Or host your published website somewhere and it should look good. 

This is because the protocol `file://` is not supported by Silex published websites. Instead all assets, scripts and styles have "protocol agnostic URLs" so that you can host your published files behind `http://` and `https://`

**Comment by darthswad** [comment]
ah, okay, I will try to put it up somewhere in order to view it then. Thank you!

**Comment by donixa-com** [comment]
I had the same it was missing css in thepublished file. I manually copied it into the folder but something was off with publishing. I had a ton of issues my first try. Finally I opened Silex in 2 browsers one with fresh copy/fresh directories made and one with broken site and changed settings and copied all the content over. Worked like a charm.

**Comment by darthswad** [comment]
lexoya's advice fixed it. When i actually published it somewhere as an html site, instead of click on the index in my file manager, it worked, showed up perfectly.

**Comment by donixa-com** [comment]
Thats good. I did everything wrong on my first try.
