### ISSUE TITLE
Adding silex to website to allow user to create a page?

### ISSUE THREAD

**Issue by dimentox** [silexlabs/Silex#449]
How would one go about using your toolkit to embed it into a editable user profile page?
I would like to save it to a db and have it display. So how can I embed your app basically then tell it where and how to save?

**Comment by lexoyo** [comment]
hello

the server side of silex is made with a library callwd unifile (https://github.com/silexlabs/unifile)

with unifile, the user can authorize silex to access his Dropbox or ftp and expose to silex methods to list folders, upload images, read and write html files (which can be real files and folders like with ftp or a database) ... you can add a service to unifile so that the user can authorize silex to read/write to his account on your platform 

or you could use unifile in your website to let the user access his Dropbox or ftp and select his site made with Silex for you to upload to s3 or somewhere... 

there are probably other options ... your use case is interesting

**Comment by lexoyo** [comment]
Here are the docs to do that

* https://github.com/silexlabs/Silex/wiki/Data-Storage
* https://github.com/silexlabs/Silex/wiki/Silex-for-hosting-providers
* https://github.com/silexlabs/Silex/wiki/Integrate-Silex-with-your-infrastructure
