### ISSUE TITLE
Problem with FTP client and Silex Editor

### ISSUE THREAD

**Issue by LightningRacer** [silexlabs/Silex#482]
It seems that the FTP client I am using does not provide data fast enough for the Silex editor. When I try to open a file, the website loads, but does not complete loading. Certain textures and pictures will end up missing, and Silex won't let me publish or save.

I've found a workaround - Saving files to DropBox, downloading them, and manually uploading to the server. DropBox transfers the data fast enough. However, this is tedious. I'm wondering if Silex has a timeout that is stopping it from pulling all of the data off of the server?

By the way, my server host is GoDaddy and the website in question is apexfrc.com

I'm having another issue with certain items scaling incorrectly, but that can wait.

Thank you!

**Comment by lexoyo** [comment]
hi @LightningRacer 
nice website !!!

> I've found a workaround - Saving files to DropBox, downloading them, and manually uploading to the server. DropBox transfers the data fast enough. However, this is tedious. I'm wondering if Silex has a timeout that is stopping it from pulling all of the data off of the server?

no, but I guess the browser has one... does it load when you preview the files (url which looks like `http://editor.silex.me/api/1.0/ftp/exec/get/..../....html`)?

> I'm having another issue with certain items scaling incorrectly, but that can wait.

no problem, please open other issues

> By the way, my server host is GoDaddy and the website in question is apexfrc.com

I see you have added this rule, and I guess it is to prevent horizontal scroll on mobile...
```
html {
    overflow-x: hidden;
}
```
The problem is that you have 2 vertical scroll bars in desktop version sometimes, so you probably want to add this rule for mobile only, so that would be
```
@media (max-width: 480px) {
  html {
    overflow-x: hidden;
  }
}

```

**Comment by devoldski** [comment]
Hi, Regarding FTP i also have some trouble with the FTP client in Silex, have tried both preprod.silex.me  and editor.silex.me.

I experience that the FTP client hangs  so i cant change path for saving  items.  The freeze also makes the editor dysfunctional. Would it be possible to have multiple ftp settings/bookmarks that users can set themselves and swap between what is active ?

I see that i would like at least two bookmarks, one for my dev env, and one for my prod env.

Also being able to manually set and change ftp details without connecting to the server would make it easier to change settings and not have the editor to crash/freeze due to connectivity issues. 

Im generally using chrome on mac, win and linux.

cheers

**Comment by lexoyo** [comment]
This is strange because FTP is usually quite fast :-/
Also the team (of volunteers) is about to launch a new version of the file browser, build from the ground up, so maybe the issue will be solved. And there is a cache system to speed up things.
Can you try to access FTP with the new version? Here is a temporary demo (work in progress)
https://cloud-explorer2.herokuapp.com/

**Comment by lexoyo** [comment]
well forget it, the ftp is not yet working on the demo, i'll have to update it, i'll let you know

**Comment by LightningRacer** [comment]
@lexoyo Thank you so much for your help! I think I'll wait for the new version as I'm not very code-proficient and barely know my way around HTML, let alone FTP stuffs.

**Comment by LightningRacer** [comment]
@lexoyo Follow-up, I tried the new demo and got a blank screen when I opened the index. Don't know if that's just because the new Cloud Explorer doesn't have FTP completely integrated or if it's just not working...

**Comment by lexoyo** [comment]
Yes it is normal, the new Cloud Explorer is not functional yet unfortunately
We are working on it on our free time so it will take a few months I guess...

**Comment by devoldski** [comment]
I have another wish for the FTP-explorer, It would be nice to have an option to add what path the explorer should work in, We have our sites  on a shared system with a large number of users and the cloud explorer tend to time out when trying opening folders containg many items / and or with limited rights, which makes it useless for us.

**Comment by lexoyo** [comment]
hmm ok... could you try this and tell me if it solves your problem of path?
https://cloud-explorer2.herokuapp.com/

note that this is a very early stage version, a work in progress. click on "select one html file" and double click on ftp and then go to your folder. try to refresh and browse back to different folders, it should not timeout and be more fluid

**Comment by devoldski** [comment]
@lexoyo sorry for my belated reply, the cloud-explorer as of nov 15. seems to be working much smoother and quicker. if you want me to do some more testing let me know.

**Comment by devoldski** [comment]
Just tried the current FTP exlplorer in editor.silex.me and I still have trouble using the FTP client in a shared env.

I suggest that you add an option to add path for root directory/working directory, that would make it much easier to use.

Either a separate field for the  path or be able to use path in server settings eg. ftp://ftp.host.tld/path/to/working/dir/

**Comment by lexoyo** [comment]
Hello!
We plan to integrate the new version of cloud explorer in Silex soon. This will solve this issue since it "rememberd" the folders and paths

**Comment by devoldski** [comment]
Ok cool, will it also be possible to add path when creating the connection?

**Comment by lexoyo** [comment]
I don't think cloud explorer has this feature

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
