### ISSUE TITLE
silex won't resize to fit browser when scaling down

### ISSUE THREAD

**Issue by letsdrinkjuice** [silexlabs/Silex#498]
Hey I'm having problems getting the content of a website I'm working on to resize with the browser window. 
![screen shot 2016-10-12 at 16 07 59](https://cloud.githubusercontent.com/assets/18750037/19317625/82098eac-909d-11e6-9284-8175565382fa.png)
The divs remained fixed when adjusting browser size, note the right border edge is cut off and the viewer must scroll right to view. this div is set to max-width:100% which is how it appears when the page is first loaded. the above screen shot is once i've made the browser smaller

![screen shot 2016-10-12 at 16 06 54](https://cloud.githubusercontent.com/assets/18750037/19317667/b227b8ca-909d-11e6-9ff0-94593ca2639c.png)
![screen shot 2016-10-12 at 16 07 07](https://cloud.githubusercontent.com/assets/18750037/19317684/c2f3b7ee-909d-11e6-90fe-de2a7c0a14ff.png)

The code only seems to resize once it hits the media query point of the mobile version, where it will then fill the browser when upscaling but will lose the inherited auto width once you begin downscaling again.

I have tried setting max-width to 100% / auto but something within silex seems to be overriding my code.

any suggestions to what im missing appreciated!

**Comment by singchan** [comment]
hi @letsdrinkjuice 
the body width in silex for now is fixed, i mean it does not change size with window resize, so when you resize the window you are supposed to reload the page
this is due to the fact that elements are "position: absolute" in desktop view so body width/height has no meaning
is that your problem?

**Comment by letsdrinkjuice** [comment]
thanks @singchan that's good to know but on the website there are a two example silex sites that  achieve it. @Stuff31 how did you achieve this? any idea on when this featured will be added?
www.bluey-creation.fr 
http://www.leofrancia.fr/

**Comment by lexoyo** [comment]
hi again @letsdrinkjuice 

http://www.bluey-creation.fr and http://www.leofrancia.fr/ are made with a previous version of silex, before the mobile editor

I am not sure I understand your concerns: the user's browser will rarely change its size and if it does, the user can scroll or refresh... is it a problem to you?

**Comment by letsdrinkjuice** [comment]
From a UX perspective, omitting such a web standard and expecting the end-user to 'refresh' or 'scroll' is a highly regressive move. I understood, I was just confused as to why your words didn't correlate with the examples on the site that showcased what could be possible with silex. Misleading. 

A client had actually approached me to add responsiveness to his silex site, but I will now have to advise him to head elsewhere to achieve this outcome. Good luck with the project in future, more focus on user experience definitely needed - your response shows current lack of consideration!

**Comment by lexoyo** [comment]
I will definitely look into it today and fix it soon if I find a way to do that easily

But I hope that I have understood well... You say that the size of the body (and width:100%) should be re-evaluated when the browser width changes?

**Comment by lexoyo** [comment]
And please note that we have few feedback from users and even fewer from professional designers
Feedback is very precious to us, so thank you

**Comment by lexoyo** [comment]
@letsdrinkjuice I have been working on this today, and indeed it was not complicated to make the body resize while resizing the window. It used to be like that but the problem was that 100% width elements were messing with the body size computation. See the [changes I made to fix it](https://github.com/lexoyo/Silex/commit/976b33d0c2088d3d9fef0a3a8b07df1d475d87e0)

You can test it on http://preprod.silex.me and it will be live on silex.me in a few days or so

I am still unsure whether this is what was bothering you, but anyway it feels better like this and a small change

**Comment by lexoyo** [comment]
And to test it, you can open your website, just save it, preview it, and resize the window to see how it behaves

**Comment by lexoyo** [comment]
@letsdrinkjuice ca you confirm this issue with body size is fixed?
If not plz re-open
