### ISSUE TITLE
A new version of Silex testers needed

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#512]
As said in the issue #283 I need beta testers for this new version of Silex. 

[Test this new version here](http://preprod.silex.me/) and comment bellow. 

Thank you!!! :love_letter:

**Comment by antosilex** [comment]
Good idea to offer several templates or blank pages from start, but there are so much things that i don't know what to test ...
My first comment would be that i don't know how to come back to the "Create a website" page after opening any publication, it should be in the file menu isn't it ?

TEMPLATES
the info links under the templates are not active (404)
I tried to modify templates it looks ok for me (but i don't understand where the existing assets are saved)

BLANK LAYOUTS
I was used to the grey background so for me the blank one seems a little confusing, but it could be just a new habit to take

NARROW
The Width value for all "metacontainers" is stil 0 instead of 960

ALL
when i resize an image and then Undo it the image disappears (the image container is still there but empty)
Still the Html Box 100% issue
Some issue when i try to show a section only in one page, it disappears

RESPONSIVE
It's just Desktop with the mobile editor enabled isnt' it ?

**Comment by lexoyo** [comment]
> My first comment would be that i don't know how to come back to the "Create a website" page after opening any publication, it should be in the file menu isn't it ?

it comes back to it when you do "new website" but I can change it to "new website from template"? or simply "Dashboard".. what do you think?

> TEMPLATES
> the info links under the templates are not active (404)

yes we need to add a README file to each template - easy since there is an issue for each template and we just need to copy/paste/rewrite a little (help wanted)

> I tried to modify templates it looks ok for me (but i don't understand where the existing assets are saved)

it saves only the HTML at first. then it will download everything when you publish

> NARROW
> The Width value for all "metacontainers" is stil 0 instead of 960

this will be fixed soon

> ALL
> when i resize an image and then Undo it the image disappears (the image container is still there but empty)

aouch, this is a new bug, thx

> Still the Html Box 100% issue

this will be fixed soon

> Some issue when i try to show a section only in one page, it disappears

I need more info to reproduce this, please open another issue

> RESPONSIVE
> It's just Desktop with the mobile editor enabled isnt' it ?

yes exactly

thank you @antosilex, bug report and tests are very useful

**Comment by ceubri** [comment]
Really nice new interface, good job !

BUG : container disappear (chrome, win7)
- i create a blank desktop (same bug with narrow)
- i create a new container
- i change bg color
- i try to scale > impossible he is no more selected, he is backward....

**Comment by lexoyo** [comment]
> BUG : container disappear (chrome, win7)
> - i create a blank desktop (same bug with narrow)
> - i create a new container
> - i change bg color
> - i try to scale > impossible he is no more selected, he is backward....

@ceubri can you confirm this is fixed on preprod.silex.me please?

**Comment by lexoyo** [comment]
Hi 

I have been working on these bugs in order to make the new version public soon.
https://github.com/silexlabs/Silex/pull/527

All your bugs (except "the Html Box 100% issue") are fixed, can you confirm @antosilex and @ceubri ?

And anyone who can do more tests is invited to do it now, before it goes live.. A lot of things have changed, I need help! Thank you!!
http://preprod.silex.me/

**Comment by RayPylant** [comment]
I will step forward and be your BETA TESTER for you that's if you still need one i some what new to git hub but learning fast ask if do not know . i am ready

**Comment by ceubri** [comment]
Hi,
all seems to be ok, great job !

**Comment by lexoyo** [comment]
thx @ceubri 
@RayPylant sure, you are more than welcome! You will need to learn how to use Silex first, can you go ahead and create a little website on http://preprod.silex.me/ ?

**Comment by lexoyo** [comment]
Or mayby you have already @RayPylant ?
If yes I could give you some specific tests to run?

**Comment by lexoyo** [comment]
I believe all critical bugs are fixed on preprod.silex.me
I will soon make a release and deploy to editor.silex.me

**Comment by lexoyo** [comment]
Almost there
https://twitter.com/lexoyo/status/822590414297374722

Help me test each template! (and there is a new free template)
http://preprod.silex.me/

**Comment by lexoyo** [comment]
Done, it is online now
https://editor.silex.me/

All the tests you can do are welcome! Thank you for your contributions, it was very helpful!
