### ISSUE TITLE
Local Install failed with Prodotype - Windows

### ISSUE THREAD

**Issue by codveda** [silexlabs/Silex#574]
Hi Local install on windows failed with below error. Can you please check and help me out.

> prodotype@1.0.0 build:editor F:\Srinivas\learning\builders\Silex\prodotype
> browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib

'bin' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prodotype@1.0.0 build:editor: `browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib`
npm ERR! Exit status 1

**Comment by JbIPS** [comment]
Hello, 

It looks like you're not executing the command from the right place. In which directory are you and what exactly are you running?

Thanks

**Comment by codveda** [comment]
Hi,

Ignore the above path, I have tried from Silex root folder and getting below error. 


$ npm install

> prodotype@1.0.0 postinstall F:\Srinivas\learning\builders\Silex\node_modules\prodotype
> npm run build:editor


> prodotype@1.0.0 build:editor F:\Srinivas\learning\builders\Silex\node_modules\prodotype
> browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib

'bin' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prodotype@1.0.0 build:editor: `browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prodotype@1.0.0 build:editor script 'browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prodotype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prodotype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prodotype
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2017-03-24T05_34_59_263Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN Error: EPERM: operation not permitted, scandir 'F:\Srinivas\learning\builders\Silex\node_modules\babel-helper-define-map\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'F:\Srinivas\learning\builders\Silex\node_modules\babel-helper-define-map\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'F:\\Srinivas\\learning\\builders\\Silex\\node_modules\\babel-helper-define-map\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prodotype@1.0.0 postinstall: `npm run build:editor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prodotype@1.0.0 postinstall script 'npm run build:editor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prodotype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:editor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prodotype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prodotype
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2017-03-24T05_35_48_826Z-debug.log

**Comment by lexoyo** [comment]
Hi
Can you try to edit this file
node_modules\prodotype\package.json

And replace this
browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] &&
bin/appendejslib

With this
browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && node
bin/appendejslib

I do not have Windows so I can not test it myself

On Mar 24, 2017 6:40 AM, "codveda" <notifications@github.com> wrote:

Hi,

Ignore the above path, I have tried from Silex root folder and getting
below error.

$ npm install

prodotype@1.0.0 postinstall F:\Srinivas\learning\builders\
Silex\node_modules\prodotype
npm run build:editor

prodotype@1.0.0 build:editor F:\Srinivas\learning\builders\
Silex\node_modules\prodotype

browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] &&
bin/appendejslib

'bin' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prodotype@1.0.0 build:editor: browserify src/Prodotype.js -o
pub/prodotype.js -t [ babelify ] && bin/appendejslib
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prodotype@1.0.0 build:editor script 'browserify
src/Prodotype.js -o pub/prodotype.js -t [ babelify ] && bin/appendejslib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prodotype
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! browserify src/Prodotype.js -o pub/prodotype.js -t [ babelify ] &&
bin/appendejslib
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR! npm bugs prodotype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls prodotype
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean
to install?

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\lenovo\AppData\Roaming\npm-cache_logs\2017-
03-24T05_34_59_263Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0
(node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})
npm WARN Error: EPERM: operation not permitted, scandir
'F:\Srinivas\learning\builders\Silex\node_modules\
babel-helper-define-map\node_modules'
npm WARN at Error (native)
npm WARN { Error: EPERM: operation not permitted, scandir
'F:\Srinivas\learning\builders\Silex\node_modules\
babel-helper-define-map\node_modules'
npm WARN at Error (native)
npm WARN errno: -4048,
npm WARN code: 'EPERM',
npm WARN syscall: 'scandir',
npm WARN path: 'F:\Srinivas\learning\builders\Silex\node_modules\
babel-helper-define-map\node_modules' }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prodotype@1.0.0 postinstall: npm run build:editor

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prodotype@1.0.0 postinstall script 'npm run
build:editor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prodotype
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm run build:editor
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR! npm bugs prodotype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls prodotype
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\lenovo\AppData\Roaming\npm-cache_logs\2017-
03-24T05_35_48_826Z-debug.log

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/silexlabs/Silex/issues/574#issuecomment-288938168>, or mute
the thread

**Comment by codveda** [comment]
Hi  lexoyo,
After "npm install" command failed with error stated above, prodotype folder from npm_modules has been deleted. Couldn't able to follow the step you have given.

Regards

**Comment by lexoyo** [comment]
Oh ok I see. You can still checkout this repo somewhere 
https://github.com/silexlabs/Prodotype

Then make the change to package.json and use npm link to use it instead of the original prodotype.. Something like this:
```
$ cd /path/to/Prodotype/
$ npm link
$ cd /path/to/Silex/
$ npm link prodotype
```

**Comment by singchan** [comment]
Or you can change Silex/package.json to use my fork of Prodotype
https://github.com/singchan/Prodotype

This means in Silex package.json, replace `silexlabs/Prodotype` by `singchan/Prodotype`
Then try again

**Comment by codveda** [comment]
Hi lexoyo,

Some how I managed to fork Prodotype and made changes, now that issue resolved. However I am getting below error and trying to resolve, please see if you can find a way out to it.

> mkdir -p dist/client/libs/prodotype/components && cp node_modules/prodotype/pub/prodotype.js node_modules/prodotype/pub/prodotype-logo-small.png dist/client/libs/prodotype/ && prodotype src/components dist/client/libs/prodotype/components/

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Silex@0.8.0 build:prodotype: `mkdir -p dist/client/libs/prodotype/components && cp node_modules/prodotype/pub/prodotype.js node_modules/prodotype/pub/prodotype-logo-small.png dist/client/libs/prodotype/ && prodotype src/components dist/client/libs/prodotype/components/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Silex@0.8.0 build:prodotype script 'mkdir -p dist/client/libs/prodotype/components && cp node_modules/prodotype/pub/prodotype.js node_modules/prodotype/pub/prodotype-logo-small.png dist/client/libs/prodotype/ && prodotype src/components dist/client/libs/prodotype/components/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,

**Comment by singchan** [comment]
try to do the same as before, add "node":
```
mkdir -p dist/client/libs/prodotype/components && cp node_modules/prodotype/pub/prodotype.js node_modules/prodotype/pub/prodotype-logo-small.png dist/client/libs/prodotype/ && node node_modules/prodotype/bin/prodotype src/components dist/client/libs/prodotype/components/
```

**Comment by codveda** [comment]
Hi Singchan,

I shall try it out in a fresh installation. As of now I have excluded this step in build process and performed the step manually. Now the system is up and running. 

Regards

**Comment by lexoyo** [comment]
ok great
I have cleaned up package.json and hopefully it works on widows again. If someone can test, I'll be happy to help
