### ISSUE TITLE
Local installation with npm simply don't work

### ISSUE THREAD

**Issue by Leznodc** [silexlabs/Silex#576]
The process is far too complex : you have to fight with versions of various modules and tools, npm variations and bugs. I'll won't try gain anyway.

**Comment by lexoyo** [comment]
hi
it looks pretty standard to me (clone, npm i, npm start)
please state which modules or tool are you talking about
i will reopen the issue when you give more details

**Comment by Leznodc** [comment]
I am pretty not able to do so ! Although I downloaded the ".zip" tarball of the project, installation script tries to connect to github for cloning I don't know what and that fails I don't know why. I am not going to debug all mysteries of proxies.

**Comment by lexoyo** [comment]
hi @Leznodc 

the ".zip" method will not work since it does not include the submodules

the easy way is to [use docker as instructed here](https://github.com/silexlabs/Silex#recommended-with-docker) **OR** the less easy way is to [use the command line as described here](https://github.com/silexlabs/Silex#local-installation-on-linux-or-macos-or-cloud9) (or [for windows instructions are here](https://github.com/silexlabs/Silex#local-installation-on-windows))

in both cases you will be able to use silex on http://localhost:6805/
is this what you need or do you simply want to use [Silex Labs ready to use instance](https://editor.silex.me/)?

**Comment by lexoyo** [comment]
hi @Leznodc 
feel free to reopen the issue if it is not solved
i will definitely help you with that
