### ISSUE TITLE
"I can not open this website. It is a published version of a Silex website. "

### ISSUE THREAD

**Issue by dhrumilbshah** [silexlabs/Silex#580]
Hi..
I have made a Website on Silex & saved in my Drobox A/C.
Now I want to do some editing but it shows error. "I can not open this website. It is a published version of a Silex website."

Please help me out.
![silex_error](https://cloud.githubusercontent.com/assets/26059398/24827807/8a6c9a8c-1c6e-11e7-95fb-7d2f654fbbf6.png)

**Comment by lexoyo** [comment]
Hi @dhrumilbshah 

In Silex, there is 2 types of html files: 
* the ones which are editable and a work in progress
* the published ones, which are created by Silex when you publish

The published ones are always called `index.html` and they can not be edited by Silex since they are optimized for the web and they do not contain all the necessary data to edit them
 
So the most likely is that you called the editable file `index.html` and then published which replaced the editable file with the published one. Is it correct? If it is the case then you need to go in dropbox, look at your html file history and revert it to before you published
