### ISSUE TITLE
Responsive Mode?

### ISSUE THREAD

**Issue by rayj00** [silexlabs/Silex#590]
How do you save in responsive mode?   When I resize the window now, the content is jacked up, but in responsive mode, all  is ok!

Thanks,

Ray

**Comment by lexoyo** [comment]
Hi ray
Same as desktop mode, just stem+s or "cloud" icône and save
You can put your website online so that I can see what's​ wrong?

On Apr 28, 2017 4:03 PM, "rayj00" <notifications@github.com> wrote:

How do you save in responsive mode? When I resize the window now, the
content is jacked up, but in responsive mode, all is ok!

Thanks,

Ray

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/silexlabs/Silex/issues/590>, or mute the thread

**Comment by rayj00** [comment]
All of the sudden I cannot publish?

Ray

**Comment by rayj00** [comment]
What do you mean by stem+s
Published site is here:  https://editor.silex.me/api/1.0/dropbox/exec/get/website/index.html
Resize the window and the pages gets messed up.

**Comment by singchan** [comment]
Sorry, stem+s was Ctrl+S

Oh ok now I understand, you can save but mobile version is messed up?

I can not see the link you gave since it is on your Dropbox. You can share
it with netlify, grrrhost! or GitHub pages for example (these are
simplified hosting services)

See silex wiki for info about this ok?

On Apr 28, 2017 4:48 PM, "rayj00" <notifications@github.com> wrote:

What do you mean by stem+s
Published site is here: https://editor.silex.me/api/1.
0/dropbox/exec/get/website/index.html
Resize the window and the pages gets messed up.

—

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/silexlabs/Silex/issues/590#issuecomment-298018398>, or mute
the thread

**Comment by rayj00** [comment]
I don't understand how to publish so you can see it?

**Comment by lexoyo** [comment]
You can make a zip file with your HTML site and the assets (in Dropbox right click, download)

Then upload it on 
lexoyo.me/GrrHost/

**Comment by rayj00** [comment]
Here:  http://lexoyo.me/GrrHost/38650/

 

If you resize the webpage window you will see it is not responsive.

 

Thanks,


Ray

**Comment by lexoyo** [comment]
it looks like you have added a border to the sections background
it is a good idea for desktop mode, but you should remove it for mobile mode (go to mobile editor and set boder width to 0)

**Comment by lexoyo** [comment]
hi @rayj00 
did you try my solution?
feel free to re-open this issue

**Comment by rayj00** [comment]
Here is the website.  Try making the window smaller.  No responsive!

 

Ray

**Comment by lexoyo** [comment]
There is no link in your message

**Comment by rayj00** [comment]
http://lexoyo.me/GrrHost/24663/

**Comment by lexoyo** [comment]
Ok so it worked

**Comment by rayj00** [comment]
Did you try to resize the window?

**Comment by lexoyo** [comment]
I opened the site on my phone
Why? It doesn't behave like it should?

**Comment by rayj00** [comment]
I thought responsive means if I resize the window on my PC, the content will resize automatically?

It does not.

 

Ray

**Comment by lexoyo** [comment]
The breaking point in silex is at 480px. Bellow this width it does resize width the browser window

**Comment by rayj00** [comment]
Is there some way I can send you  a video so you can see what I mean?

**Comment by singchan** [comment]
Sure, you can put it on YouTube maybe?

**Comment by rayj00** [comment]
Ok , look at this video.   https://youtu.be/53plGfIC_H0

As I resize the window, shouldn’t the content change size also?

 

Thanks,

 

Ray

**Comment by lexoyo** [comment]
I see what you mean
For the mobile version to activate you need to resize your window even smaller. Then you will see a responsive version of your website

**Comment by rayj00** [comment]
You are using the mobile example a lot, but  should “responsive” include resizing the window in a PC?  There are many different sizes and resolutions of monitors out there.  So for example someone might have 1024x768 resolution, someone else 1920x1080, etc.  browsing for each one will show differently.  The page should resize automatically to cover all resolutions, right?

 

Thanks,


Ray

**Comment by singchan** [comment]
> You are using the mobile example a lot, but  should “responsive” include resizing the window in a PC?  > There are many different sizes and resolutions of monitors out there.  So for example someone might have 1024x768 resolution, someone else 1920x1080, etc.  browsing for each one will show differently.  The page should resize automatically to cover all resolutions, right?

yes you are right
the idea is to choose when to switch to responsive mode, and in responsive mode it adapts to the window size
for now reponsive is width < 480px but I hope that we will have other breakpoints or at least be able to change the 480px value
all suggestions welcome and I will take time to do it if we find a good solution
