### ISSUE TITLE
Best IDE to develop Silex with

### ISSUE THREAD

**Issue by simsdavis** [silexlabs/Silex#596]
Is there a certain IDE like Eclipse I should be using to edit the source code with?

**Comment by JbIPS** [comment]
Hello @simsdavis! This is no restriction on IDE for Silex contribution. Since it's written in Javascript, any editor/IDE that supports it will do just fine 😄. Most of us use [Sublime Text](https://www.sublimetext.com/), [Atom](https://atom.io/) or [VisualCode](https://code.visualstudio.com/).

I'm using Vim and I know some even use Eclipse, so use the one you're most confident with!

**Comment by lexoyo** [comment]
hi @simsdavis 
if you have more question feel free to re-open the issue
