### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by berserk82** [silexlabs/Silex#602]
Does Silex require anything but a webserver to run? (eg: node, frameworks, etc)

**Comment by lexoyo** [comment]
Hi!

The websites you create with silex can be hosted anywhere since it is just HTML CSS Javascript. No requirement

The tool itself, silex editor, requires nodejs to run. To be compiled you need Java too, see the versions in the readme 

You are welcome to share with us what you are doing with silex :)

**Comment by berserk82** [comment]
Thanks.
