### ISSUE TITLE
Why not Haxe?

### ISSUE THREAD

**Issue by fullofcaffeine** [silexlabs/Silex#665]
Pretty awesome project you've got here! I'm wondering though, with the history of Silex with `Haxe`, and considering the size of this project, why haven't you guy used it? I'd be really interested to know why you judged plain JS/ES6 was a better choice.

**Comment by lexoyo** [comment]
Hi @ffullofcaffeine nice to see you around here
In 2012 I started the v2 of silex from scratch with several goals, one of them being to make it easy to contribute to. Because silex is a tool for designers so we have very few contributors (mainly because users do not know code but also because the contribution and open ecosystem is new to most designers who are more used to freemium and cracked software, which makes silex very important to bring our vision of freedom to these great people ;)

So I tried and partly failed to remove any friction in the setup process of the development environment, make the code as explicit as possible, minimise inheritance, avoid dependencies etc... Also Haxe js was not as good as it is now. This is why I made this painful choice to go with vanilla javascript.

I have switched most of the code to es6 and use closure compiler to type check and detect errors, so it is not as hard as maintaining jquery based js...

Very good question, thx. Please ask more and be critical if somethings seems wrong to you

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
