### ISSUE TITLE
Unable to import any files

### ISSUE THREAD

**Issue by tommy-qiu** [silexlabs/Silex#677]
When I click import it takes me to a blank gray screen, (happened yesterday). Can't import anything now.

![screen shot 2018-01-08 at 9 00 03 am](https://user-images.githubusercontent.com/26195773/34674052-705e6ec4-f452-11e7-828d-01fc8b130b0e.png)

**Comment by Lea75** [comment]
me too :(

**Comment by lexoyo** [comment]
I'm still working on it :'(

**Comment by lexoyo** [comment]
OK I GOT IT
This was a nightmare... It works now
The bug comes from a service we use to enable HTTPS on preprod.silex.me which is called [cloudflare](https://www.cloudflare.com/). By default it changes the javascript to speed it up... And in our case, since recently it breaks CloudExplorer... So I disabled it and now it works
Sorry about that, I should have tested after deploying
You can test now

**Comment by Lea75** [comment]
Merci !! Thank u 👍
