### ISSUE TITLE
silex.me

### ISSUE THREAD

**Issue by ckmsmission** [silexlabs/Silex#681]
I am using silex .me to create the website .I am not able to see the menu (file, edit.....) on my editor ,please help to add menu on my editor

**Comment by lexoyo** [comment]
Hi
This was in an older version of silex. Now there are icons on the left instead of text menu.
Please let me know where you saw this so that we can fix the docs
Bye
-- 
Alex Hoyau
+33(0)676683806
Skype: alex.hoyau

**Comment by ckmsmission** [comment]
![image](https://user-images.githubusercontent.com/35676975/35214534-78cad0bc-ff87-11e7-95c3-f0ff74405a47.png)
not able to add any file to my dropbox

**Comment by lexoyo** [comment]
Yes dropbox change it's API, a lot of posts here about that
Please use the version under development (beta) on https://preprod.silex.me

**Comment by ckmsmission** [comment]
not able to upload anything

**Comment by ckmsmission** [comment]
![image](https://user-images.githubusercontent.com/35676975/35218717-a91a3d8a-ff95-11e7-8e6b-0e0ffa248970.png)

**Comment by lexoyo** [comment]
Chrome blocked the popup :(
We should display a message, it is a work in progress
But simply allow the popup and it will work
![screenshot from 2018-01-24 20-57-30](https://user-images.githubusercontent.com/715377/35354049-4b77de84-0149-11e8-8ffd-428dbe6a584c.png)

**Comment by lexoyo** [comment]
This issue is already here
https://github.com/silexlabs/CloudExplorer2/issues/39

I guess this is because we delay the opening of the popup now:
https://github.com/silexlabs/CloudExplorer2/blob/master/src/js/UnifileService.js#L161

This was changed by @JbIPS in order to be async
https://github.com/silexlabs/CloudExplorer2/blame/master/src/js/UnifileService.js#L161
