### ISSUE TITLE
Not possible to install on windows

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#812]
Node-expat cannot be installed on Windows 10, so Silex cannot be installed on Windows. Thats my experience nowday. :(
Does anybode know any workaround or so?

**Comment by JbIPS** [comment]
Windows 10 supports Docker engine, safest solution is to install it and run Silex in a Linux container

**Comment by jotakar** [comment]
Indeed I didn't try Docker. Sorry. But I supose Docker has to install node-expat too and this package (node-expat) doesn't work with Windows.  Or am I wrong?
Finally I've installed  it in my local linux server, to study and check it. 
My first idea is get a way to local store for preview and a way to download the source straight. 
Thanks

**Comment by JbIPS** [comment]
Actually Docker will do the mapping between the Linux container and the Windows host. As far as Silex is concerned, you're running Linux so everything will be fine.

I'll close this since it looks like you found a solution but feel free to open another issue if you experience issues with Docker.

Thank you for using Silex
