### ISSUE TITLE
Payload too large - anyone?

### ISSUE THREAD

**Issue by Tomygg** [silexlabs/Silex#819]
I have crated a website with Silex and sometimes, when I want to savo additional data, I get an error message: "Payload too large". What does it mean? I use Dropbox and Silex cloud. Not desktop version.

**Comment by lexoyo** [comment]
Is it when you save your website?
Can you share the HTML page please?
And try saving it to github
Also check your quota on Dropbox

**Comment by Tomygg** [comment]
Yes, when I try to save the website. 
The html I cannot share, it's still unpublished.

**Comment by Tomygg** [comment]
The html: http://www.tb.lt/tb_naujas/index.html
Sometimes it happens, when I try to save a new page, but right now it always happens when I try inserting slideshow. If I delete the slideshow, then I can save the progress, but just when I add slideshow and try saving the website, the error pops up. What's wrong with it? Is this Silex platform limited to how large is the website or how many pages there are?

**Comment by Tomygg** [comment]
And by the way, my quota on Dropbox is OK, there is bunch of free space there.

**Comment by lexoyo** [comment]
Thank you for the bug report, I found that the max allowed weight for the files to be saved was 1Mo, and yours reached it. This is a recent limit. I pushed it to 10Mo as you can see here
https://github.com/silexlabs/Silex/pull/823/commits/6b1cd9e447f3bc6856f07ddc138a072948d74592

The fix should be live soon on editor.silex.me

However the fact that your page is so heavy is not normal, I looked at the code and saw a lot of data coming from copy/paste from Microsoft Word, like this:
https://github.com/lexoyo/tb.lt/blob/master/index.html#L194

The "preprod" version of silex (soon to be released and testable on https://preprod.silex.me) has a fix for that. This is because it has a better text editor which filters useless tags. And there is also a new "style editor" so the way to style texts is different you will see. To fix this problem you will need to open your website with https://preprod.silex.me and to double click each text field of your website. This will remove the unwanted tags, but also the bad formatting so your texts will look bad but this is ok. Then style all your texts at once with the new style editor. As this is a new feature, create a copy of your html page (with save as for example) and please comment on the thread where we test this new feature: https://github.com/silexlabs/Silex/issues/662

Side note: be careful if you call your html page "index.html" and then publish in the same folder it will overwrite index.html with the published (uneditable) version

**Comment by Tomygg** [comment]
Thanx! It's all good now, and I cleaned up my pages. Thank you, Lexoyo.
