### ISSUE TITLE
Using Silex as a way to quickly create/edit and deploy landing pages, questions

### ISSUE THREAD

**Issue by fullofcaffeine** [silexlabs/Silex#871]
Hi @lexoyo and team,

I've checked Silex a few years ago and it has come a long way! Thanks for keeping it up and keeping it free and open :)

I'd like to use Silex to create or edit fully static sites as an alternative to Middleman (the Ruby static site generator), for example. I think it could be great to quickly come up with landing pages to test ideas fast (a mix between unbounce and wix). Most of the time, I don't need the complexity of a site generator or a dynamic backend, and just need to get something (beautiful and functional) out there, fast to show and collect some data (i.e emails). 

I have a couple of questions regarding that:
1) I've read Silex can only edit pages created by it. Is this format documented somewhere? What is the metadata that it needs specifically? 
2) I haven't seen any way to edit the HTML source code of the page in Silex, am I missing something or is it not possible?
2) I'd like to host Silex myself and use it to quickly create and modify static sites. I currently use Ansible to provision new nginx vhosts in a server, so the workflow that I'm looking for would look like:
 3.1) I provision the new vhost / domain with ansible;
 3.2) I fire up my own hosted Silex and create a new site;
 3.3) I deploy (publish it) using Silex.

In 3.3, I'd like to push it to GitHub first so that the version is tracked and just after that, I'd like Silex to update it via FTP. I can always use a build server that is triggered by GitHub, but if Silex can do it, it'd be simpler and I could skip setting up a build server. Another possibility is for Silex to push to github, I then pull locally and use something like rsync or Capistrano to deploy, this can work for now.  What do you think? I'm open to other ideas, any insights are appreciated.

**Comment by lexoyo** [comment]
Hello @fullofcaffeine !!
It's great to see you back with lots of good ideas :)

As a matter of fact I am using silex for my business too so I recently added several features to customize Silex - for freelancers to create optimized versions of silex to fit their production needs and for hosting companies to integrate with their infrastructure. So these questions comes right in time!

> I'd like to use Silex to create or edit fully static sites as an alternative to Middleman (the Ruby static site generator), for example. I think it could be great to quickly come up with landing pages to test ideas fast (a mix between unbounce and wix). Most of the time, I don't need the complexity of a site generator or a dynamic backend, and just need to get something (beautiful and functional) out there, fast to show and collect some data (i.e emails).

A mix between unbounce and wix, that is exactly what it is. And it integrates with Jekyll now, more on that bellow

>    I've read Silex can only edit pages created by it. Is this format documented somewhere? What is the metadata that it needs specifically?
>    I haven't seen any way to edit the HTML source code of the page in Silex, am I missing something or is it not possible?

This is the answer which you will not like: the pages have special markup and a JSON object with params in it. Also in the editable version, the whole webisite pages are included in 1 single page. This is all cleaned up when the user publishes the website to host it online (it is split in multiple pages and json data is removed, as well as useless css classes etc.

But the real problem is that Silex has something special in order to provide the best editing experience, I decided that in the desktop editor, everything would be absolute. This makes it very easy to design like in photoshop or powerpoint, not like in dreamweaver... This is the same with wix. And not the same with the excellent [grapejs](https://grapesjs.com/) which is an alternative to Silex (the only one I would consider).  

So about that topic

1- it very is complex to write a script to convert any website to a silex ediatble template
2- it is very quick (less than 4h) to "silexsize" a website (clone it starting from scratch)

>    I'd like to host Silex myself and use it to quickly create and modify static sites. I currently use Ansible to provision new nginx vhosts in a server, so the workflow that I'm looking for would look like:
>    3.1) I provision the new vhost / domain with ansible;
>    3.2) I fire up my own hosted Silex and create a new site;
>    3.3) I deploy (publish it) using Silex.
> In 3.3, I'd like to push it to GitHub first so that the version is tracked and just after that, I'd like Silex to update it via FTP. I can always use a build server that is triggered by GitHub, but if Silex can do it, it'd be simpler and I could skip setting up a build server. Another possibility is for Silex to push to github, I then pull locally and use something like rsync or Capistrano to deploy, this can work for now. What do you think? I'm open to other ideas, any insights are appreciated.

I didn't know about ansible.. It looks complex to me, I am not a good ops.

It is easy to [host an instance of Silex](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex)

Also very easy: you could save your website on github so that it is versioned. And setup the publication to push to an sFTP or your local machine (local works only if you use the [ofline/desktop version of Silex](https://github.com/silexlabs/Silex/releases)).

Please feel free to ask, your use case is very interesting and I am willing to make it work for you.
A few links to the roadmap which might be interesting to you:

* [Silex for marketers](https://github.com/silexlabs/Silex/milestone/10)
* feature request: standard set of components: #702
* [Silex for hosting companies](https://github.com/silexlabs/Silex/milestone/4)

**Comment by lexoyo** [comment]
Hi @fullofcaffeine 

Following your comment about unbounce, I watched this video series about unbounce and Silex does exactly all that, for free and even better. I think we should do the same video series with Silex

Part 1: The first video will cover choosing a theme, breaking it into sections, and then writing the copy for the video. https://www.youtube.com/watch?v=Nvehej4k6VM

Part 2: The second video will show you how to move all your written copy to your chosen theme and set it up for both mobile and desktop use. https://youtu.be/higZzD2IR1E 

Part 3: The third video shows how to connect your Facebook ads account to your Unbounce page so that you can track conversions. How to install the code and where to put it. https://youtu.be/zgSZsQ1m11s

Also I make a series of online workshops in french for freelancers who sell Silex websites but it is in french
https://www.meetup.com/Ateliers-du-libre-et-de-lopen-source/events/258110084/

**Comment by fullofcaffeine** [comment]
Hi Alex, thanks a lot of the very comprehensive replies! I didn't have the
time to go through them but will do so this week.

**Comment by lexoyo** [comment]
Hello
Did you manage to do what you want?
Can you tell me more about your use case?

**Comment by fullofcaffeine** [comment]
Hi @lexoyo,

Apologies for the delay. I think I got what I wanted here, which basically was more info on how to use Silex as a landing page generator and bounce up some ideas about it. If I have any other specific questions, I'll ask through new issues.

Thanks a lot for the comprehensive replies, by the way, and keep up the great work!
