### ISSUE TITLE
FTP problem

### ISSUE THREAD

**Issue by Imageny** [silexlabs/Silex#918]
Hi, I'm having a problem here. When I log in to Silex via the FTP, it gives me the Invalid credentials error. I legit entered the password properly, and not even restarting Silex or changing the password of the FTP helped! This is driving me insane! I would appreciate ANY help!

**Comment by lexoyo** [comment]
@jbIPS if you have time?
I can not look at this error before 2 weeks :-/
I think it might be the same issue as the webdav one?

**Comment by JbIPS** [comment]
Hi! Could you give us some information to reproduce, like Silex version (I understood you have your own instance), any logs output and the FTP server you're using? 
I'll try to reproduce and fix this quickly.
Thank you for the report 😃

**Comment by Imageny** [comment]
I use the most recent Silex version. Unfortunately I don't have any logs. The FTP server i'm using is files.000webhost.com.

**Comment by JbIPS** [comment]
Thank you but it's unclear if you use our live version of Silex (on http://editor.silex.me/) or you installed your own on your server. Not wrong answer, we'll help anyway 😁

**Comment by Imageny** [comment]
I use the live version.

**Comment by lexoyo** [comment]
you may have to transfer everything by hand for now 
@JbIPS did you have time to investigate? do you need more info?

**Comment by JbIPS** [comment]
I was able to reproduce but didn't find the bug yet. I'll have more time next week

**Comment by lexoyo** [comment]
I had a look into this

What I found was that the `stat` of unifile FTP service probably never worked. I suppose with some version of FTP server it did @JbIPS ? But I find the method not very logical in any case

What was done:

```
	stat(session, path, ftpSession) {
		return callAPI(session, 'ls', ftpSession, path)
		.then((entries) => {
			// Not found
			if(entries.length === 0) throw new UnifileError(UnifileError.ENOENT, 'Not found');
			// It's a file
			if(entries.length === 1) return toFileInfos(entries[0]);
			// It's a folder
			const lastTime = entries.reduce((memo, stat) => {
				// eslint-disable-next-line no-param-reassign
				if(stat.time > memo) memo = stat.time;
				return memo;
			}, 0);
			return toFileInfos({
				name: path.split('/').pop(),
				type: 1,
				time: lastTime
			});
		});
	}

```

So first if the folder exists but is empty it will throw an error "Not found"

Then the other problem is that if the folder does not exist it seems to return an empty array too... 

What I would find more logical than all this is to list the parent folder and return reald data about the file (size, real change date..)

But I did something even more straightforward as I am in a hurry, I used the `list` FTP action instead of `ls`, which is more low level and returns a string if the folder exists but throws an error if not...

PS: the unit tests fail for sftp but I did not touch anything more than ftp :(
PPS: I published to npm as I don't think anyone has time to review this

**Comment by lexoyo** [comment]
PPPS: If someone does have time please test :)
