### ISSUE TITLE
Silex is resposive in pc browser when resized, why not it compatable with mobile phones?

### ISSUE THREAD

**Issue by bsde1234** [silexlabs/Silex#962]
Silex is resposive in pc browser when resized, why not it compatable with mobile phones? Can I use silex in mobile phone browsers?

**Comment by lexoyo** [comment]
Hi
Websites created with Silex are compatible with mobile phone browsers and yes you can use them on mobile
:+1:

**Comment by bsde1234** [comment]
Actually I was asking about silex editor site, not the sites created with silex.

**Comment by lexoyo** [comment]
Oh ok
It is missing a few things to work properly on mobile, including touch support for the menu and the stage, zoom, properties as a pop-in,... It is far from easy because of the UX 

I would suggest that you design the website with silex on the desktop but you can use it with Jekyll. Then you plug a headless cms to edit the content on mobile. The easiest headless cms are siteleaf.com and stastic.net but more advanced are strapi and contentful

To use silex with Jekyll, please use the beta version of silex on preprod.silex.me and publish for Jekyll. Each silex page will be a Jekyll layout. You need to learn Jekyll though
