### ISSUE TITLE
imported fonts are not taking

### ISSUE THREAD

**Issue by aracnoid149** [silexlabs/Silex#973]
I have been attempting to import a font using both CSS and the fonts section under website settings.  The font does not seem to take no matter how I change the code in CSS or alter the paths from which I am importing the font in the settings.

**Comment by lexoyo** [comment]
Hello
Can you share what you put in the font manager (website settings)
Also did you apply the font to texts in the style manager ?
New fonts are tricky, I'll look for the docs and tell you what to read

**Comment by aracnoid149** [comment]
Here is the link to the font in question:
https://www.onlinewebfonts.com/download/53062a13ae4416854e325ea9f587cc1a

in the font manager I put the following for the link:
https://db.onlinewebfonts.com/c/53062a13ae4416854e325ea9f587cc1a?family=MicrogrammaDBolExt
in the name, I called it "MicrogrammaDBolExt"

in the CSS File, I added the following:
@import url(https://db.onlinewebfonts.com/c/53062a13ae4416854e325ea9f587cc1a?family=MicrogrammaDBolExt);

@font-face {font-family: "MicrogrammaDBolExt"; src: url("https://db.onlinewebfonts.com/t/53062a13ae4416854e325ea9f587cc1a.eot"); src: url("https://db.onlinewebfonts.com/t/53062a13ae4416854e325ea9f587cc1a.eot?#iefix") format("embedded-opentype"), url("https://db.onlinewebfonts.com/t/53062a13ae4416854e325ea9f587cc1a.woff2") format("woff2"), url("https://db.onlinewebfonts.com/t/53062a13ae4416854e325ea9f587cc1a.woff") format("woff"), url("https://db.onlinewebfonts.com/t/53062a13ae4416854e325ea9f587cc1a.ttf") format("truetype"), url("https://db.onlinewebfonts.com/t/53062a13ae4416854e325ea9f587cc1a.svg#MicrogrammaDBolExt") format("svg"); }

**Comment by lexoyo** [comment]
Ok, so I tried it and this is what **should** work:

> in the font manager I put the following for the link:
> https://db.onlinewebfonts.com/c/53062a13ae4416854e325ea9f587cc1a?family=MicrogrammaDBolExt
> in the name, I called it "MicrogrammaDBolExt"

+ add a text box, set the font MicrogrammaDBolExt in it's styles:
![screenshot_20191026_145016](https://user-images.githubusercontent.com/715377/67623804-ef98cb00-f7ff-11e9-8adc-17fb3de5666d.png)

But the problem is that onlinewebfonts.com do not support https when a font is embeded with the #1 method (which is what silex does i guess)
![screenshot_20191026_145116](https://user-images.githubusercontent.com/715377/67623824-1d7e0f80-f800-11e9-9c09-41e61a040079.png)

So would you consider using a site such as https://fontlibrary.org ?

**Comment by aracnoid149** [comment]
Hello, sorry for the late response.  I managed to get fonts imported from google fonts.  Thank you for your help.
